server:
  port: 8072
 
eureka:
  instance:
    preferIpAddress: true
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://eurekaserver:8070/eureka/
      
 
spring:
  cloud:
    loadbalancer.ribbon.enabled: false
    gateway:
        routes:
        - id: smartenergy
          uri: lb://smartenergy
          predicates:
            - Path=/smartenergy/**
          filters:
            - RewritePath=/smartenergy/(?<path>.*), /$\{path}


       
management:
  endpoints:
    web:
      exposure:
        include: "*"
        
        