server:
  port: 8072
 
eureka:
  instance:
    preferIpAddress: true
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://eurekaserver:8070/eureka/
      
 
spring:
  cloud:
    loadbalancer.ribbon.enabled: false
    gateway:
        routes:
        - id: smartenergy
          uri: lb://smartenergy
          predicates:
            - Path=/smartenergy/**
          filters:
            - RewritePath=/smartenergy/(?<path>.*), /$\{path}
        - id: smartenergycustomer
          uri: lb://smartenergycustomer
          predicates:
            - Path=/smartenergycustomer/**
          filters:
            - RewritePath=/smartenergycustomer/(?<path>.*), /$\{path}
            - RemoveRequestHeader=Cookie,Set-Cookie


       
management:
  endpoints:
    web:
      exposure:
        include: "*"
        
        